### ISSUE TITLE
Data Exporter will not start after setup

### ISSUE THREAD

**Issue by bpahern** [MD2Korg/mCerebrum-CerebralCortex#1]
At the end of the setup process in the study app, after setting userID and wake/sleep times, when I click to start all applications, Data Exporter will not start. It appears to be crashing.

**Comment by joy1130** [comment]
Data exporter is crashing due to userID or studyId not being saved to the dataKit

**Comment by twhnat** [comment]
This commit fixes this crash problem.
https://github.com/MD2Korg/mCerebrum-CerebralCortex/commit/c57d459451ad701390790bf342727eb102a8650c
